[package]
name = "oblivious-syncing-service"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-poly = "0.5.0"
ark-std = "0.5.0"
ark-ff = "0.5.0"
ark-bls12-377 = "0.5.0"
ark-ec = "0.5.0"
ark-serialize = "0.5.0"
sha2 = "0.10"
lazy_static = "1.4"
rand = "0.8.5"
anyhow = "1.0.98"
